sudo: false
language: node_js
node_js:
  - node
  - "10.4.0"
branches:
  only:
    - master
install:
  - npm install
  - npm install -g codecov
cache:
  directories:
    - node_modules
script:
  - npm run test
after_success:
  - codecov